Prueba Tecnica/Models/SALARIO.cs
//------------------------------------------------------------------------------
// Entity data model asociado a la base de datos, corresponde a la estructura de
// tabla llamada SALARIO en la base de datos
//------------------------------------------------------------------------------

namespace Prueba_Tecnica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SALARIO
    {
        public int ID { get; set; }
        //Esta anotación permite cambiar del nombre con el que el usuario visualiza la columna de la tabla, afecta unicamete a la vista
        [Display(Name = "Empleado")]
        public string EMPLEADO { get; set; }
        [Display(Name = "Salario Bruto")]
        public Nullable<decimal> SALARIO_BRUTO { get; set; }
        [Display(Name = "Monto deducible")]
        public Nullable<decimal> MONTO_DEDUCIBLE { get; set; }
        [Display(Name = "Pensión")]
        public Nullable<decimal> PENSION { get; set; }
        [Display(Name = "Embargo 1")]
        public Nullable<decimal> EMBARGO1 { get; set; }
        [Display(Name = "Embargo 2")]
        public Nullable<decimal> EMBARGO2 { get; set; }
        [Display(Name = "Rebajo Pensión")]
        public Nullable<decimal> REBAJO_PENSION { get; set; }
        [Display(Name = "Rebajo Embargos")]
        public Nullable<decimal> REBAJO_EMBARGO { get; set; }
    }
}

Prueba Tecnica/Models/Salario.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Tecnica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaDB : DbContext
    {
        public PruebaDB()
            : base("name=PruebaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SALARIO> SALARIO { get; set; }
    }
}

Prueba Tecnica/Models/Salario.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\kiramz10-PC\Desktop\Prueba Tecnica\Prueba Tecnica\Models\Salario.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Prueba Tecnica/Models/Salario1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Prueba Tecnica/Controllers/SalarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prueba_Tecnica.Models;
using Prueba_Tecnica.Services;

namespace Prueba_Tecnica.Controllers
{
    public class SalarioController : Controller
    {
        //Declarar el servicio
        private SalarioService salarioService;


        //Constructor del controlador
        public SalarioController()
        {
            //Inicializar el servicio
            this.salarioService = new SalarioService();
        }

        // GET: Salario
        // Pagina principal del controlador
        // @Return ActionResult: retorna una vista @Index con una lista de objetos de tipo SALARIO
        public ActionResult Index()
        {
            return View(this.salarioService.ObtenerTodos());
        }


        // GET: Salario/Create
        // Redirecciona a la vista para crear objetos de tipo SALARIO
        // @Return ActionResult: retorna la vista @Create
        public ActionResult Create()
        {
            return View();
        }



        // POST: Salario/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        // Realiza la acción de creación de un objeto de tipo SALARIO
        // @Param SALARIO salario: objeto de tipo SALARIO que incluye del formulario únicamente los campos "EMPLEADO,SALARIO_BRUTO,PENSION,EMBARGO1,EMBARGO2"
        // @Return ActionResult: retorna a la vista @Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EMPLEADO,SALARIO_BRUTO,PENSION,EMBARGO1,EMBARGO2")] SALARIO salario)
        {
            if (ModelState.IsValid)
            {
               
                this.salarioService.Create(salario);
                return RedirectToAction("Index");
            }

            return View(salario);
        }



        // GET: Salario/Delete/5
        // Redirecciona a la vista de eliminación de empleados, busca el registro mediante el id.
        // @Param int id, default 0: corresponde al id del objeto de tipo SALARIO a eliminar, el valor por defecto es 0 y devuelve un badrequest dado que no es valido
        // @Return ActionResult: retorna a la vista @Delete
        public ActionResult Delete(int id = 0)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            SALARIO salario = this.salarioService.ObtenerPorId(id);
            if (salario == null)
            {
                return HttpNotFound();
            }
            return View(salario);
        }

        // POST: Salario/Delete/5
        // Realiza la acción de eliminar un objeto de tipo SALARIO
        // @Param int id: corresponde al id del objeto de tipo SALARIO a eliminar y devuelve un badrequest dado que no es valido
        // @Return ActionResult: retorna a la vista @Index
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            this.salarioService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Prueba Tecnica/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Prueba Tecnica/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Prueba Tecnica/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Prueba Tecnica/Views/Salario/Create.cshtml
@model Prueba_Tecnica.Models.SALARIO

@{
    ViewBag.Title = "Agregar empleado";
}

<h2>Agregar empleado</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Información del empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SALARIO_BRUTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SALARIO_BRUTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SALARIO_BRUTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PENSION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PENSION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PENSION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMBARGO1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMBARGO1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMBARGO1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMBARGO2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMBARGO2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMBARGO2, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prueba Tecnica/Views/Salario/Delete.cshtml
@model Prueba_Tecnica.Models.SALARIO

@{
    ViewBag.Title = "Eliminar empleado";
}

<h2>Eliminar empleado</h2>

<h3>Estas seguro de querer eliminar esta información?</h3>
<div>
    <h4>Información del empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EMPLEADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMPLEADO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SALARIO_BRUTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SALARIO_BRUTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MONTO_DEDUCIBLE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MONTO_DEDUCIBLE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PENSION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PENSION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMBARGO1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMBARGO1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMBARGO2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMBARGO2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.REBAJO_PENSION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REBAJO_PENSION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.REBAJO_EMBARGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REBAJO_EMBARGO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

Prueba Tecnica/Views/Salario/Index.cshtml
@model IEnumerable<Prueba_Tecnica.Models.SALARIO>

@{
    ViewBag.Title = "Lista de empleados";
}

<h2>Lista de empleados</h2>

<p>
    @Html.ActionLink("Crear otro", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EMPLEADO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SALARIO_BRUTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MONTO_DEDUCIBLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PENSION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMBARGO1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMBARGO2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REBAJO_PENSION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REBAJO_EMBARGO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EMPLEADO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SALARIO_BRUTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MONTO_DEDUCIBLE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PENSION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMBARGO1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMBARGO2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.REBAJO_PENSION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.REBAJO_EMBARGO)
        </td>
        <td>
            @Html.ActionLink("Borrar", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Prueba Tecnica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Embargo del Salario", "Index", "Salario", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Prueba Técnica ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>